# Generated by Django 4.2.9 on 2024-01-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_password_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
