# Generated by Django 4.2.9 on 2024-02-04 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_review_author_alter_review_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='projects_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
