# Generated by Django 4.2.9 on 2024-02-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_project_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
    ]
