# Generated by Django 4.2.9 on 2024-02-04 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_project_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='projects_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
