# Generated by Django 4.2.9 on 2024-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Student', 'Student'), ('Freelancer', 'Freelancer'), ('Educator', 'Educator'), ('University', 'University')], max_length=50),
        ),
    ]
