# Generated by Django 4.2.9 on 2024-04-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='country',
        ),
    ]
