# Generated by Django 4.2.9 on 2024-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_rename_location_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.TextField(blank=True),
        ),
    ]
