# Generated by Django 4.2.9 on 2024-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Student', 'Student'), ('Freelancer', 'Freelancer'), ('Educator', 'Educator'), ('University', 'University'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
