# Generated by Django 4.2 on 2024-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_personaldetails_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], max_length=7, null=True),
        ),
    ]
