# Generated by Django 4.2 on 2024-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_personaldetails_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu_degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_group_or_major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.ManyToManyField(to='data.edu_degree')),
            ],
        ),
        migrations.AddField(
            model_name='edu_degree',
            name='level',
            field=models.ManyToManyField(to='data.edu_level'),
        ),
    ]
