# Generated by Django 4.2 on 2024-05-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_edu_degree_id_alter_edu_group_or_major_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu_degree',
            name='level',
        ),
        migrations.AddField(
            model_name='edu_degree',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.edu_level'),
        ),
    ]
