# Generated by Django 4.2 on 2024-05-13 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_edu_degree_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.edu_degree'),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa_scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.edu_group_or_major'),
        ),
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.edu_level'),
        ),
        migrations.AddField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='result_type',
            field=models.CharField(blank=True, choices=[('Grade', 'Grade'), ('Class', 'Class'), ('Division', 'Division')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
