# Generated by Django 4.2 on 2024-07-10 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_project_participants_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edu_degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edu_group_or_major'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.edu_level'),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='result_type',
            field=models.CharField(choices=[('Grade', 'Grade'), ('Class', 'Class'), ('Division', 'Division')], max_length=8),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('institution_name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=50)),
                ('duration_year', models.IntegerField()),
                ('duration_month', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
