# Generated by Django 4.2 on 2024-07-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_education_degree_alter_education_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
