# Generated by Django 4.2 on 2024-07-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_rename_end_data_training_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='duration_days',
            new_name='duration_day',
        ),
    ]
