# Generated by Django 4.2 on 2024-07-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='department',
            field=models.CharField(default='ll', max_length=250),
            preserve_default=False,
        ),
    ]
