# Generated by Django 4.2 on 2024-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_university_universityprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
