# Generated by Django 4.2 on 2024-07-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
