# Generated by Django 4.2 on 2024-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_university_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
