# Generated by Django 4.2 on 2024-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_university_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprogram',
            name='program_type',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate'), ('Professional', 'Professional'), ('Certificate', 'Certificate'), ('Doctoral', 'Doctoral')], default='Graduate', max_length=50),
            preserve_default=False,
        ),
    ]
