# Generated by Django 4.2 on 2024-07-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_universityprogram_program_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityprogram',
            old_name='program_type',
            new_name='type',
        ),
    ]
