# Generated by Django 5.0.7 on 2024-07-15 21:29

import django.db.models.deletion
from django.db import migrations, models
# Generated by Django 4.2 on 2024-07-15 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_remove_course_description_remove_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselecture',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.course'),
            preserve_default=False,
        ),
    ]
