# Generated by Django 5.0.7 on 2024-07-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
